In [9]:
import numpy as np
import random
from sklearn.utils import shuffle

%load_ext autoreload
%autoreload 2

from Node import Node
from SumNode import SumNode
from ProductNode import ProductNode
from Node import LeafNode
from SPN import SPN

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


# Discriminitive
### XOR example

In [2]:
x1 = np.array([0.0,0.0])
x2 = np.array([0.0,1.0])
x3 = np.array([1.0,0.0])
x4 = np.array([1.0,1.0])

x5 = np.array([0.0,0.0])
x6 = np.array([0.0,1.0])
x7 = np.array([1.0,0.0])
x8 = np.array([1.0,1.0])

y = np.array([0,0,0,0,1,1,1,1])

In [7]:
spn = SPN()
# root node id = 0
root_node = SumNode(0, 0)
spn.add_node(root_node)

# Product nodes 1 and 2
prod_node1 = ProductNode(1, 0)
prod_node2 = ProductNode(2, 0)
spn.add_node(prod_node1, random.randint(1,9))
spn.add_node(prod_node2, random.randint(1,9))

# Sum nodes 3 - 6
sum_node3 = SumNode(3,1)
sum_node4 = SumNode(4,2)
sum_node5 = SumNode(5,1)
sum_node6 = SumNode(6,2)
spn.add_node(sum_node3)
spn.add_node(sum_node4)
spn.add_node(sum_node5)
spn.add_node(sum_node6)

# Add leaf nodes
X1 = LeafNode(7,np.array([1]), 0, False)
X_1 = LeafNode(8,np.array([2]), 0, True)
X2 = LeafNode(9,np.array([3,4]), 1, False)
X_2 = LeafNode(10,np.array([3,4]), 1, True)
X3 = LeafNode(11,np.array([5,6]), 2, False)
X_3 = LeafNode(12,np.array([5,6]), 2, True)
spn.add_node(X1, random.randint(1,9))
spn.add_node(X_1, random.randint(1,9))
spn.add_node(X2, random.randint(1,9))
spn.add_node(X_2, random.randint(1,9))
spn.add_node(X3, random.randint(1,9))
spn.add_node(X_3, random.randint(1,9))
spn.normalise_weights()
spn.print_weights()


Node ID 0
To node 1 :    0.1250
To node 2 :    0.8750

Node ID 3
To node 9 :    0.1667
To node 10 :    0.8333

Node ID 4
To node 9 :    0.1667
To node 10 :    0.8333

Node ID 5
To node 11 :    0.4375
To node 12 :    0.5625

Node ID 6
To node 11 :    0.4375
To node 12 :    0.5625


### Forward pass untrained

In [8]:
print(spn.query(x1))
print(spn.query(x2))
print(spn.query(x3))
print(spn.query(x4))
print(spn.query(x5))
print(spn.query(x6))
print(spn.query(x7))
print(spn.query(x8))
print()
spn.print_weights()

[ 0.72916698  0.43750001  0.56249999]
[ 0.14583347  0.43750001  0.56249999]
[ 0.10416678  0.43750001  0.56249999]
[ 0.02083337  0.43750001  0.56249999]
[ 0.72916698  0.43750001  0.56249999]
[ 0.14583347  0.43750001  0.56249999]
[ 0.10416678  0.43750001  0.56249999]
[ 0.02083337  0.43750001  0.56249999]


Node ID 0
To node 1 :    0.1250
To node 2 :    0.8750

Node ID 3
To node 9 :    0.1667
To node 10 :    0.8333

Node ID 4
To node 9 :    0.1667
To node 10 :    0.8333

Node ID 5
To node 11 :    0.4375
To node 12 :    0.5625

Node ID 6
To node 11 :    0.4375
To node 12 :    0.5625


In [12]:
data = np.array([x1,x2,x3,x4,x5,x6,x7,x8])

print("Training...\n")
for i in range(10):
    spn.discriminitive_hard_gd(data, y)


print("Probability x1",spn.query(x1))
print("Probability x2",spn.query(x2))
print("Probability x3",spn.query(x3))
print("Probability x4",spn.query(x4))
print("Probability x5",spn.query(x5))
print("Probability x6",spn.query(x6))
print("Probability x7",spn.query(x7))
print("Probability x8",spn.query(x8))


spn.print_weights()

Training...



NameError: name 'best_guess' is not defined