In [1]:
import numpy as np
import random
from sklearn.utils import shuffle

%load_ext autoreload
%autoreload 2

from Node import Node
from SumNode import SumNode
from ProductNode import ProductNode
from Node import LeafNode
from SPN import SPN

# Discriminitive
### XOR example

In [2]:
x1 = np.array([0.0,0.0])
x2 = np.array([0.0,1.0])
x3 = np.array([1.0,0.0])
x4 = np.array([1.0,1.0])

x5 = np.array([0.0,0.0])
x6 = np.array([0.0,1.0])
x7 = np.array([1.0,0.0])
x8 = np.array([1.0,1.0])

y = np.array([0,0,0,0,1,1,1,1])

In [3]:
spn = SPN()
# root node id = 0
root_node = SumNode(0, 0)
spn.add_node(root_node)

# Product nodes 1 and 2
prod_node1 = ProductNode(1, 0)
prod_node2 = ProductNode(2, 0)
spn.add_node(prod_node1, random.randint(1,9))
spn.add_node(prod_node2, random.randint(1,9))

# Sum nodes 3 - 6
sum_node3 = SumNode(3,1)
sum_node4 = SumNode(4,2)
sum_node5 = SumNode(5,1)
sum_node6 = SumNode(6,2)
spn.add_node(sum_node3)
spn.add_node(sum_node4)
spn.add_node(sum_node5)
spn.add_node(sum_node6)

# Add leaf nodes
X1 = LeafNode(7,np.array([1]), 0, False)
X_1 = LeafNode(8,np.array([2]), 0, True)
X2 = LeafNode(9,np.array([3,4]), 1, False)
X_2 = LeafNode(10,np.array([3,4]), 1, True)
X3 = LeafNode(11,np.array([5,6]), 2, False)
X_3 = LeafNode(12,np.array([5,6]), 2, True)
spn.add_node(X1, random.randint(1,9))
spn.add_node(X_1, random.randint(1,9))
spn.add_node(X2, random.randint(1,9))
spn.add_node(X_2, random.randint(1,9))
spn.add_node(X3, random.randint(1,9))
spn.add_node(X_3, random.randint(1,9))
spn.normalise_weights()
spn.print_weights()


Node ID 0
To node 1 :    0.2500
To node 2 :    0.7500

Node ID 3
To node 9 :    0.5625
To node 10 :    0.4375

Node ID 4
To node 9 :    0.5625
To node 10 :    0.4375

Node ID 5
To node 11 :    0.4286
To node 12 :    0.5714

Node ID 6
To node 11 :    0.4286
To node 12 :    0.5714


### Forward pass untrained

In [8]:
print(spn.query(x1))
print(spn.query(x2))
print(spn.query(x3))
print(spn.query(x4))
print(spn.query(x5))
print(spn.query(x6))
print(spn.query(x7))
print(spn.query(x8))
print()
spn.print_weights()

[ 0.328125    0.42857143  0.57142857]
[ 0.421875    0.42857143  0.57142857]
[ 0.109375    0.42857143  0.57142857]
[ 0.140625    0.42857143  0.57142857]
[ 0.328125    0.42857143  0.57142857]
[ 0.421875    0.42857143  0.57142857]
[ 0.109375    0.42857143  0.57142857]
[ 0.140625    0.42857143  0.57142857]


Node ID 0
To node 1 :    0.2500
To node 2 :    0.7500

Node ID 3
To node 9 :    0.5625
To node 10 :    0.4375

Node ID 4
To node 9 :    0.5625
To node 10 :    0.4375

Node ID 5
To node 11 :    0.4286
To node 12 :    0.5714

Node ID 6
To node 11 :    0.4286
To node 12 :    0.5714


In [10]:
data = np.array([x1,x2,x3,x4,x5,x6,x7,x8])

print("Training...\n")
for i in range(10):
    spn.discriminitive_hard_gd(data, y)
    #spn.discriminitive_soft_gd(data, y)


print("Probability x1",spn.query(x1))
print("Probability x2",spn.query(x2))
print("Probability x3",spn.query(x3))
print("Probability x4",spn.query(x4))
print("Probability x5",spn.query(x5))
print("Probability x6",spn.query(x6))
print("Probability x7",spn.query(x7))
print("Probability x8",spn.query(x8))


spn.print_weights()

Training...

id 1 difference 0
id 2 difference 0
id 9 difference 4
id 10 difference 4
id 9 difference 4
id 10 difference 4
id 11 difference 4
id 12 difference 4
id 11 difference 4
id 12 difference 4
id 1 difference 0
id 2 difference 0
id 9 difference 4
id 10 difference 4
id 9 difference 4
id 10 difference 4
id 11 difference 4
id 12 difference 4
id 11 difference 4
id 12 difference 4
id 1 difference 0
id 2 difference 0
id 9 difference 4
id 10 difference 4
id 9 difference 4
id 10 difference 4
id 11 difference 4
id 12 difference 4
id 11 difference 4
id 12 difference 4
id 1 difference 0
id 2 difference 0
id 9 difference 4
id 10 difference 4
id 9 difference 4
id 10 difference 4
id 11 difference 4
id 12 difference 4
id 11 difference 4
id 12 difference 4
id 1 difference 0
id 2 difference 0
id 9 difference 4
id 10 difference 4
id 9 difference 4
id 10 difference 4
id 11 difference 4
id 12 difference 4
id 11 difference 4
id 12 difference 4
id 1 difference 0
id 2 difference 0
id 9 difference 4
id 

# Example 2

In [13]:
# generate new dataset
x1 = np.array([0.0,0.0,0.0])
x2 = np.array([0.0,0.0,1.0])
x3 = np.array([0.0,1.0,0.0])
x4 = np.array([0.0,1.0,1.0])

x5 = np.array([1.0,0.0,0.0])
x6 = np.array([1.0,0.0,1.0])
x7 = np.array([1.0,1.0,0.0])
x8 = np.array([1.0,1.0,1.0])

data = []
y = []
for i in range(10):
    data.append(x1)
    y.append(0)
for i in range(90):
    data.append(x2)
    y.append(0)
for i in range(10):
    data.append(x3)
    y.append(0)
for i in range(90):
    data.append(x4)
    y.append(0)
for i in range(224):
    data.append(x5)
    y.append(0)
for i in range(336):
    data.append(x6)
    y.append(0)
for i in range(96):
    data.append(x7)
    y.append(0)
for i in range(144):
    data.append(x8)
    y.append(0)
# make arrays
data = np.array(data)
y = np.array(y)

#data = shuffle(data, random_state=0)
print(data.shape)
print(y.shape)

(1000, 3)
(1000,)


In [14]:
spn = SPN()
# root node id = 0
root_node = SumNode(0, 0)
spn.add_node(root_node)

# Product nodes 1 and 2
prod_node1 = ProductNode(1, 0)
prod_node2 = ProductNode(2, 0)
spn.add_node(prod_node1, random.randint(1,9))
spn.add_node(prod_node2, random.randint(1,9))

# Sum nodes 3 - 6
sum_node3 = SumNode(3,1)
sum_node4 = SumNode(4,2)
sum_node5 = SumNode(5,1)
sum_node6 = SumNode(6,2)
spn.add_node(sum_node3)
spn.add_node(sum_node4)
spn.add_node(sum_node5)
spn.add_node(sum_node6)

# Add leaf nodes
X1 = LeafNode(7,np.array([1]), 0, False)
X_1 = LeafNode(8,np.array([2]), 0, True)
X2 = LeafNode(9,np.array([3,4]), 1, False)
X_2 = LeafNode(10,np.array([3,4]), 1, True)
X3 = LeafNode(11,np.array([5,6]), 2, False)
X_3 = LeafNode(12,np.array([5,6]), 2, True)
spn.add_node(X1,  np.array([random.randint(1,9)]) )
spn.add_node(X_1, np.array([random.randint(1,9)]))
spn.add_node(X2, np.array([random.randint(1,9), random.randint(1,9)]) )
spn.add_node(X_2, np.array([random.randint(1,9), random.randint(1,9)]))
spn.add_node(X3, np.array([random.randint(1,9), random.randint(1,9)]))
spn.add_node(X_3, np.array([random.randint(1,9), random.randint(1,9)]))

spn.normalise_weights()
spn.print_weights()


Node ID 0
To node 1 :    0.2500
To node 2 :    0.7500

Node ID 3
To node 9 :    0.5000
To node 10 :    0.5000

Node ID 4
To node 9 :    0.8182
To node 10 :    0.1818

Node ID 5
To node 11 :    0.5714
To node 12 :    0.4286

Node ID 6
To node 11 :    0.8000
To node 12 :    0.2000


In [15]:
print("Training...\n")
for i in range(10):
    spn.discriminitive_hard_gd(data, y)
    #spn.discriminitive_soft_gd(data, y)

print("Probability x1",spn.query(x1))
print("Probability x2",spn.query(x2))
print("Probability x3",spn.query(x3))
print("Probability x4",spn.query(x4))
print("Probability x5",spn.query(x5))
print("Probability x6",spn.query(x6))
print("Probability x7",spn.query(x7))
print("Probability x8",spn.query(x8))


spn.print_weights()

Training...

Probability x1 [ 0.0375  1.      1.    ]
Probability x2 [ 0.3375  1.      1.    ]
Probability x3 [ 0.0375  1.      1.    ]
Probability x4 [ 0.3375  1.      1.    ]
Probability x5 [ 0.07  1.    1.  ]
Probability x6 [ 0.105  1.     1.   ]
Probability x7 [ 0.03  1.    1.  ]
Probability x8 [ 0.045  1.     1.   ]

Node ID 0
To node 1 :    0.2500
To node 2 :    0.7500

Node ID 3
To node 9 :    0.3000
To node 10 :    0.7000

Node ID 4
To node 9 :    0.5000
To node 10 :    0.5000

Node ID 5
To node 11 :    0.6000
To node 12 :    0.4000

Node ID 6
To node 11 :    0.9000
To node 12 :    0.1000
