In [1]:
import numpy as np
import random
from sklearn.utils import shuffle

%load_ext autoreload
%autoreload 2

from Node import Node
from SumNode import SumNode
from ProductNode import ProductNode
from Node import LeafNode
from SPN import SPN

# Discriminitive
### XOR example

In [2]:
x1 = np.array([0.0,0.0])
x2 = np.array([0.0,1.0])
x3 = np.array([1.0,0.0])
x4 = np.array([1.0,1.0])

x5 = np.array([0.0,0.0])
x6 = np.array([0.0,1.0])
x7 = np.array([1.0,0.0])
x8 = np.array([1.0,1.0])

y = np.array([0,0,0,0,1,1,1,1])

In [3]:
spn = SPN()
# root node id = 0
root_node = SumNode(0, 0)
spn.add_node(root_node)

# Product nodes 1 and 2
prod_node1 = ProductNode(1, 0)
prod_node2 = ProductNode(2, 0)
spn.add_node(prod_node1, random.randint(1,9))
spn.add_node(prod_node2, random.randint(1,9))

# Sum nodes 3 - 6
sum_node3 = SumNode(3,1)
sum_node4 = SumNode(4,2)
sum_node5 = SumNode(5,1)
sum_node6 = SumNode(6,2)
spn.add_node(sum_node3)
spn.add_node(sum_node4)
spn.add_node(sum_node5)
spn.add_node(sum_node6)

# Add leaf nodes
X1 = LeafNode(7,np.array([1]), 0, False)
X_1 = LeafNode(8,np.array([2]), 0, True)
X2 = LeafNode(9,np.array([3,4]), 1, False)
X_2 = LeafNode(10,np.array([3,4]), 1, True)
X3 = LeafNode(11,np.array([5,6]), 2, False)
X_3 = LeafNode(12,np.array([5,6]), 2, True)
spn.add_node(X1, random.randint(1,9))
spn.add_node(X_1, random.randint(1,9))
spn.add_node(X2, random.randint(1,9))
spn.add_node(X_2, random.randint(1,9))
spn.add_node(X3, random.randint(1,9))
spn.add_node(X_3, random.randint(1,9))
spn.normalise_weights()
spn.print_weights()


Node ID 0
To node 1 :    0.6667
To node 2 :    0.3333

Node ID 3
To node 9 :    0.6667
To node 10 :    0.3333

Node ID 4
To node 9 :    0.6667
To node 10 :    0.3333

Node ID 5
To node 11 :    0.4286
To node 12 :    0.5714

Node ID 6
To node 11 :    0.4286
To node 12 :    0.5714


### Forward pass untrained

In [4]:
print(spn.query(x1))
print(spn.query(x2))
print(spn.query(x3))
print(spn.query(x4))
print(spn.query(x5))
print(spn.query(x6))
print(spn.query(x7))
print(spn.query(x8))
print()
spn.print_weights()

[ 0.11111111  0.42857143  0.57142857]
[ 0.22222222  0.42857143  0.57142857]
[ 0.22222222  0.42857143  0.57142857]
[ 0.44444444  0.42857143  0.57142857]
[ 0.11111111  0.42857143  0.57142857]
[ 0.22222222  0.42857143  0.57142857]
[ 0.22222222  0.42857143  0.57142857]
[ 0.44444444  0.42857143  0.57142857]


Node ID 0
To node 1 :    0.6667
To node 2 :    0.3333

Node ID 3
To node 9 :    0.6667
To node 10 :    0.3333

Node ID 4
To node 9 :    0.6667
To node 10 :    0.3333

Node ID 5
To node 11 :    0.4286
To node 12 :    0.5714

Node ID 6
To node 11 :    0.4286
To node 12 :    0.5714


In [5]:
data = np.array([x1,x2,x3,x4,x5,x6,x7,x8])

print("Training...\n")
for i in range(10):
    #spn.discriminitive_hard_gd(data, y)
    spn.discriminitive_soft_gd(data, y)


print("Probability x1",spn.query(x1))
print("Probability x2",spn.query(x2))
print("Probability x3",spn.query(x3))
print("Probability x4",spn.query(x4))
print("Probability x5",spn.query(x5))
print("Probability x6",spn.query(x6))
print("Probability x7",spn.query(x7))
print("Probability x8",spn.query(x8))


spn.print_weights()

Training...









id 1 difference 0.375
id 1 without mean 0.234375
id 2 difference 0.75
id 2 without mean 0.609375
id 9 difference 1.3125
id 9 without mean 0.8203125
id 10 difference 2.625
id 10 without mean 2.1328125
id 9 difference 1.3125
id 9 without mean 0.8203125
id 10 difference 2.625
id 10 without mean 2.1328125
id 11 difference 2.0
id 11 without mean 1.5546875
id 12 difference 1.5625
id 12 without mean 1.1171875
id 11 difference 2.0
id 11 without mean 1.5546875
id 12 difference 1.5625
id 12 without mean 1.1171875








id 1 difference 0.392830188679
id 1 without mean 0.257778594751
id 2 difference 0.687582562748
id 2 without mean 0.552530968819
id 9 difference 1.51382608696
id 9 without mean 1.06541190422
id 10 difference 2.07348737494
id 10 without mean 1.6250731922
id 9 difference 1.51382608696
id 9 without mean 1.06541190422
id 10 difference 2.07348737494
id 10 without mean 1.6250731922
id 11 difference 1.87726925282
id 11 without mean 1.43746131505
id 12 difference 1.6

# Example 2

In [2]:
# generate new dataset
x1 = np.array([0.0,0.0,0.0])
x2 = np.array([0.0,0.0,1.0])
x3 = np.array([0.0,1.0,0.0])
x4 = np.array([0.0,1.0,1.0])

x5 = np.array([1.0,0.0,0.0])
x6 = np.array([1.0,0.0,1.0])
x7 = np.array([1.0,1.0,0.0])
x8 = np.array([1.0,1.0,1.0])

data = []
y = []
for i in range(10):
    data.append(x1)
    y.append(0)
for i in range(90):
    data.append(x2)
    y.append(0)
for i in range(10):
    data.append(x3)
    y.append(0)
for i in range(90):
    data.append(x4)
    y.append(0)
for i in range(224):
    data.append(x5)
    y.append(0)
for i in range(336):
    data.append(x6)
    y.append(0)
for i in range(96):
    data.append(x7)
    y.append(0)
for i in range(144):
    data.append(x8)
    y.append(0)
# make arrays
data = np.array(data)
y = np.array(y)

#data = shuffle(data, random_state=0)
print(data.shape)
print(y.shape)

(1000, 3)
(1000,)


In [5]:
spn = SPN()
# root node id = 0
root_node = SumNode(0, 0)
spn.add_node(root_node)

# Product nodes 1 and 2
prod_node1 = ProductNode(1, 0)
prod_node2 = ProductNode(2, 0)
spn.add_node(prod_node1, random.randint(1,9))
spn.add_node(prod_node2, random.randint(1,9))

# Sum nodes 3 - 6
sum_node3 = SumNode(3,1)
sum_node4 = SumNode(4,2)
sum_node5 = SumNode(5,1)
sum_node6 = SumNode(6,2)
spn.add_node(sum_node3)
spn.add_node(sum_node4)
spn.add_node(sum_node5)
spn.add_node(sum_node6)

# Add leaf nodes
X1 = LeafNode(7,np.array([1]), 0, False)
X_1 = LeafNode(8,np.array([2]), 0, True)
X2 = LeafNode(9,np.array([3,4]), 1, False)
X_2 = LeafNode(10,np.array([3,4]), 1, True)
X3 = LeafNode(11,np.array([5,6]), 2, False)
X_3 = LeafNode(12,np.array([5,6]), 2, True)
spn.add_node(X1,  np.array([random.randint(1,9)]) )
spn.add_node(X_1, np.array([random.randint(1,9)]))
spn.add_node(X2, np.array([random.randint(1,9), random.randint(1,9)]) )
spn.add_node(X_2, np.array([random.randint(1,9), random.randint(1,9)]))
spn.add_node(X3, np.array([random.randint(1,9), random.randint(1,9)]))
spn.add_node(X_3, np.array([random.randint(1,9), random.randint(1,9)]))

spn.normalise_weights()
spn.print_weights()


Node ID 0
To node 1 :    0.4615
To node 2 :    0.5385

Node ID 3
To node 9 :    0.4667
To node 10 :    0.5333

Node ID 4
To node 9 :    0.6364
To node 10 :    0.3636

Node ID 5
To node 11 :    0.5333
To node 12 :    0.4667

Node ID 6
To node 11 :    0.7000
To node 12 :    0.3000


In [8]:
print("Training...\n")
for i in range(10):
    #spn.discriminitive_hard_gd(data, y)
    spn.discriminitive_soft_gd(data, y)
    #print()

print("Probability x1",spn.query(x1))
print("Probability x2",spn.query(x2))
print("Probability x3",spn.query(x3))
print("Probability x4",spn.query(x4))
print("Probability x5",spn.query(x5))
print("Probability x6",spn.query(x6))
print("Probability x7",spn.query(x7))
print("Probability x8",spn.query(x8))

spn.print_weights()

Training...

id 1 difference 0.0
part 1.73333333333
update from 0 to 1 without mean 0.0
id 2 difference 0.0
part 0.371428571429
update from 0 to 2 without mean 0.0
id 9 difference 3.19917510755
part 3.19917510755
update from 3 to 9 without mean 3.19917510755
id 10 difference 3.20035365557
part 3.20035365557
update from 3 to 10 without mean 3.20035365557
id 9 difference 0.760968185007
part 0.760968185007
update from 4 to 9 without mean 0.760968185007
id 10 difference 0.843252360307
part 0.843252360307
update from 4 to 10 without mean 0.843252360307
id 11 difference 3.20016021259
part 3.20016021259
update from 5 to 11 without mean 3.20016021259
id 12 difference 3.19975971119
part 3.19975971119
update from 5 to 12 without mean 3.19975971119
id 11 difference 0.835908297418
part 0.835908297418
update from 6 to 11 without mean 0.835908297418
id 12 difference 0.576944578456
part 0.576944578456
update from 6 to 12 without mean 0.576944578456
id 1 difference 0.0
part 1.73333333333
update from 0

### Should be:
#### 0: 0.8, 0.2
#### 3: 0.3, 0.7
#### 4: 0.5, 0.5
#### 5: 0.6, 0.4
#### 6: 0.9, 0.1