In [1]:
import numpy as np
import random
from sklearn.utils import shuffle

%load_ext autoreload
%autoreload 2

from Node import Node
from SumNode import SumNode
from ProductNode import ProductNode
from Node import LeafNode
from SPN import SPN

# Discriminitive
### XOR example

In [2]:
x1 = np.array([0.0,0.0])
x2 = np.array([0.0,1.0])
x3 = np.array([1.0,0.0])
x4 = np.array([1.0,1.0])

x5 = np.array([0.0,0.0])
x6 = np.array([0.0,1.0])
x7 = np.array([1.0,0.0])
x8 = np.array([1.0,1.0])

y = np.array([0,0,0,0,1,1,1,1])

In [3]:
spn = SPN()
# root node id = 0
root_node = SumNode(0, 0)
spn.add_node(root_node)

# Product nodes 1 and 2
prod_node1 = ProductNode(1, 0)
prod_node2 = ProductNode(2, 0)
spn.add_node(prod_node1, random.randint(1,9))
spn.add_node(prod_node2, random.randint(1,9))

# Sum nodes 3 - 6
sum_node3 = SumNode(3,1)
sum_node4 = SumNode(4,2)
sum_node5 = SumNode(5,1)
sum_node6 = SumNode(6,2)
spn.add_node(sum_node3)
spn.add_node(sum_node4)
spn.add_node(sum_node5)
spn.add_node(sum_node6)

# Add leaf nodes
X1 = LeafNode(7,np.array([1]), 0, False)
X_1 = LeafNode(8,np.array([2]), 0, True)
X2 = LeafNode(9,np.array([3,4]), 1, False)
X_2 = LeafNode(10,np.array([3,4]), 1, True)
X3 = LeafNode(11,np.array([5,6]), 2, False)
X_3 = LeafNode(12,np.array([5,6]), 2, True)
spn.add_node(X1, random.randint(1,9))
spn.add_node(X_1, random.randint(1,9))
spn.add_node(X2, random.randint(1,9))
spn.add_node(X_2, random.randint(1,9))
spn.add_node(X3, random.randint(1,9))
spn.add_node(X_3, random.randint(1,9))
spn.normalise_weights()
spn.print_weights()


Node ID 0
To node 1 :    0.5714
To node 2 :    0.4286

Node ID 3
To node 9 :    0.6667
To node 10 :    0.3333

Node ID 4
To node 9 :    0.6667
To node 10 :    0.3333

Node ID 5
To node 11 :    0.2857
To node 12 :    0.7143

Node ID 6
To node 11 :    0.2857
To node 12 :    0.7143


### Forward pass untrained

In [4]:
print(spn.query(x1))
print(spn.query(x2))
print(spn.query(x3))
print(spn.query(x4))
print(spn.query(x5))
print(spn.query(x6))
print(spn.query(x7))
print(spn.query(x8))
print()
spn.print_weights()

[ 0.14285714  0.28571429  0.71428571]
[ 0.28571429  0.28571429  0.71428571]
[ 0.19047619  0.28571429  0.71428571]
[ 0.38095238  0.28571429  0.71428571]
[ 0.14285714  0.28571429  0.71428571]
[ 0.28571429  0.28571429  0.71428571]
[ 0.19047619  0.28571429  0.71428571]
[ 0.38095238  0.28571429  0.71428571]


Node ID 0
To node 1 :    0.5714
To node 2 :    0.4286

Node ID 3
To node 9 :    0.6667
To node 10 :    0.3333

Node ID 4
To node 9 :    0.6667
To node 10 :    0.3333

Node ID 5
To node 11 :    0.2857
To node 12 :    0.7143

Node ID 6
To node 11 :    0.2857
To node 12 :    0.7143


In [5]:
data = np.array([x1,x2,x3,x4,x5,x6,x7,x8])

print("Training...\n")
for i in range(10):
    #spn.discriminitive_hard_gd(data, y)
    spn.discriminitive_soft_gd(data, y)


print("Probability x1",spn.query(x1))
print("Probability x2",spn.query(x2))
print("Probability x3",spn.query(x3))
print("Probability x4",spn.query(x4))
print("Probability x5",spn.query(x5))
print("Probability x6",spn.query(x6))
print("Probability x7",spn.query(x7))
print("Probability x8",spn.query(x8))


spn.print_weights()

Training...

id 1 difference 0.875
id 1 without mean -9.33333333333
id 2 difference 1.16666666667
id 2 without mean -7.0
id 9 difference 0.875
id 9 without mean -14.0
id 10 difference 1.75
id 10 without mean -7.0
id 9 difference 0.65625
id 9 without mean -10.5
id 10 difference 1.3125
id 10 without mean -5.25
id 11 difference 2.04166666667
id 11 without mean -6.53333333333
id 12 difference 0.816666666667
id 12 without mean -16.3333333333
id 11 difference 1.53125
id 11 without mean -4.9
id 12 difference 0.6125
id 12 without mean -12.25
id 1 difference 0.875
id 1 without mean -9.33333333333
id 2 difference 1.16666666667
id 2 without mean -7.0
id 9 difference 0.875
id 9 without mean -14.0
id 10 difference 1.75
id 10 without mean -7.0
id 9 difference 0.65625
id 9 without mean -10.5
id 10 difference 1.3125
id 10 without mean -5.25
id 11 difference 2.04166666667
id 11 without mean -6.53333333333
id 12 difference 0.816666666667
id 12 without mean -16.3333333333
id 11 difference 1.53125
id 11 w

# Example 2

In [6]:
# generate new dataset
x1 = np.array([0.0,0.0,0.0])
x2 = np.array([0.0,0.0,1.0])
x3 = np.array([0.0,1.0,0.0])
x4 = np.array([0.0,1.0,1.0])

x5 = np.array([1.0,0.0,0.0])
x6 = np.array([1.0,0.0,1.0])
x7 = np.array([1.0,1.0,0.0])
x8 = np.array([1.0,1.0,1.0])

data = []
y = []
for i in range(10):
    data.append(x1)
    y.append(0)
for i in range(90):
    data.append(x2)
    y.append(0)
for i in range(10):
    data.append(x3)
    y.append(0)
for i in range(90):
    data.append(x4)
    y.append(0)
for i in range(224):
    data.append(x5)
    y.append(0)
for i in range(336):
    data.append(x6)
    y.append(0)
for i in range(96):
    data.append(x7)
    y.append(0)
for i in range(144):
    data.append(x8)
    y.append(0)
# make arrays
data = np.array(data)
y = np.array(y)

#data = shuffle(data, random_state=0)
print(data.shape)
print(y.shape)

(1000, 3)
(1000,)


In [9]:
spn = SPN()
# root node id = 0
root_node = SumNode(0, 0)
spn.add_node(root_node)

# Product nodes 1 and 2
prod_node1 = ProductNode(1, 0)
prod_node2 = ProductNode(2, 0)
spn.add_node(prod_node1, random.randint(1,9))
spn.add_node(prod_node2, random.randint(1,9))

# Sum nodes 3 - 6
sum_node3 = SumNode(3,1)
sum_node4 = SumNode(4,2)
sum_node5 = SumNode(5,1)
sum_node6 = SumNode(6,2)
spn.add_node(sum_node3)
spn.add_node(sum_node4)
spn.add_node(sum_node5)
spn.add_node(sum_node6)

# Add leaf nodes
X1 = LeafNode(7,np.array([1]), 0, False)
X_1 = LeafNode(8,np.array([2]), 0, True)
X2 = LeafNode(9,np.array([3,4]), 1, False)
X_2 = LeafNode(10,np.array([3,4]), 1, True)
X3 = LeafNode(11,np.array([5,6]), 2, False)
X_3 = LeafNode(12,np.array([5,6]), 2, True)
spn.add_node(X1,  np.array([random.randint(1,9)]) )
spn.add_node(X_1, np.array([random.randint(1,9)]))
spn.add_node(X2, np.array([random.randint(1,9), random.randint(1,9)]) )
spn.add_node(X_2, np.array([random.randint(1,9), random.randint(1,9)]))
spn.add_node(X3, np.array([random.randint(1,9), random.randint(1,9)]))
spn.add_node(X_3, np.array([random.randint(1,9), random.randint(1,9)]))

spn.normalise_weights()
spn.print_weights()


Node ID 0
To node 1 :    0.7500
To node 2 :    0.2500

Node ID 3
To node 9 :    0.4375
To node 10 :    0.5625

Node ID 4
To node 9 :    0.6667
To node 10 :    0.3333

Node ID 5
To node 11 :    0.1250
To node 12 :    0.8750

Node ID 6
To node 11 :    0.5385
To node 12 :    0.4615


In [11]:
print("Training...\n")
for i in range(10):
    #spn.discriminitive_hard_gd(data, y)
    spn.discriminitive_soft_gd(data, y)
    print()

print("Probability x1",spn.query(x1))
print("Probability x2",spn.query(x2))
print("Probability x3",spn.query(x3))
print("Probability x4",spn.query(x4))
print("Probability x5",spn.query(x5))
print("Probability x6",spn.query(x6))
print("Probability x7",spn.query(x7))
print("Probability x8",spn.query(x8))

spn.print_weights()

Training...

id 1 difference 1.19620761747
id 1 without mean 1.19440758117
id 2 difference 0.603828682096
id 2 without mean 0.602028645796
id 9 difference 0.982596788315
id 9 without mean 0.980273844421
id 10 difference 1.34034710534
id 10 without mean 1.33802416145
id 9 difference 0.491826651714
id 9 without mean 0.490666018521
id 10 difference 0.668806541806
id 10 without mean 0.667645908612
id 11 difference 1.38605014642
id 11 without mean 1.38376074652
id 12 difference 0.903349755573
id 12 without mean 0.901060355671
id 11 difference 0.673380047274
id 11 without mean 0.672273057999
id 12 difference 0.433609227702
id 12 without mean 0.432502238427

id 1 difference 1.19727198074
id 1 without mean 1.19547196201
id 2 difference 0.602746752244
id 2 without mean 0.600946733511
id 9 difference 0.985941402214
id 9 without mean 0.983617278973
id 10 difference 1.33818183912
id 10 without mean 1.33585771588
id 9 difference 0.494251736079
id 9 without mean 0.493088631439
id 10 difference 0.668

### Should be:
#### 0: 0.8, 0.2
#### 3: 0.3, 0.7
#### 4: 0.5, 0.5
#### 5: 0.6, 0.4
#### 6: 0.9, 0.1